kind: Service
apiVersion: v1
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 3001 # Enduser access this port 
      targetPort: 3000 # containerPort running in the Pod